version: "3.9"

services:
  elasticlogs:
    image: vosarat/background-elasticlogs-service:0.1
    build:
      context: .
      dockerfile: Astor.Background.ElasticLogs.Service/Dockerfile
    environment:
      - RABBIT_CONNECTIONSTRING=amqp://rabbit:5672
      - ELASTIC_URL=http://elastic:9200
      - KIBANA_URL=http://kibana:5601
    depends_on:
      - rabbit
      - elastic
      - kibana
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  elastic:
    image: elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.12.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601