version: "3.4"

services:
#  elastic:
#    image: elasticsearch:7.12.1
#    environment:
#      - discovery.type=single-node
#    ports:
#    - 9200:9200
#    - 9300:9300
#  kibana:
#    image: kibana:7.12.1
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elastic:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elastic
  kibana:
    image: kibana:7.12.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
#    depends_on:
#      - elastic