version: '3.9'

services: 
  service:
    image: vosarat/background-management-service:2.0.0.1
    build:
      context: src
      dockerfile: Astor.Background.Management.Service/Dockerfile
    environment:
      - RABBIT_CONNECTIONSTRING=amqp://rabbit:5672
      - MONGO_CONNECTIONSTRING=mongodb://mongo:27017
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
      - INTERNALEXCHANGEPREFIX=my-docker
      - TIMEZONESHIFT=3
    depends_on: 
      - rabbit
      - mongo
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017