name: publish to nuget
on:
  push:
    branches:
      - nugetCI
  workflow_dispatch:
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Astor.Background/Astor.Background.csproj

          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$